name: CI
on:
  push:
    branches:
      - master

jobs:
  GenerateDocs:
    runs-on: macos-10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout Wiki
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: BOSL2.wiki

    - name: Install gifsicle
      run: brew install gifsicle

    - name: Install Pillow
      run: sudo pip3 install Pillow

    - name: Install Docsgen
      run: sudo pip3 install openscad_docsgen

    - name: Install OpenSCAD
      run: |
        curl -L -o OpenSCAD.dmg https://files.openscad.org/snapshots/OpenSCAD-2021.03.24.dmg
        hdiutil attach OpenSCAD.dmg
        cp -a /Volumes/OpenSCAD/OpenSCAD.app /Applications/

    - name: Generating Docs
      run: |
        cd $GITHUB_WORKSPACE
        export OPENSCADPATH=$(dirname $GITHUB_WORKSPACE)
        echo "::add-matcher::.github/openscad_docsgen.json"
        openscad-docsgen -m -i -t -c -I *.scad
        cd BOSL2.wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        git commit -m "Wiki docs auto-regen." && git push || true

    - name: Bump Release Version
      run: |
        cd $GITHUB_WORKSPACE
        ./scripts/increment_version.sh
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add version.scad
        git commit -m "Bump release version." && git push || true

